### ISSUE TITLE
User authentication (base)

### ISSUE THREAD

**Issue by aleskandro** [silviabooks/scala-project#10]
Rileggendo le specifiche, abbiamo la necessita' di fornire un minimo di meccanismo di autenticazione.

Dobbiamo fare qualche prova su una delle risorse gia' definite affinche' in funzione del tipo di utente (un flag admin : bool) si proceda o si risponda con un 401.

In sostanza penso serva definire una route come /login che crei qualcosa utilizzabile a mo' di autenticazione negli header http successivi (la piu' semplice direi tra auth basic, digest, session, qualunque cosa di indolore).

Dopo di questo abbiamo praticamente finito la parte server-side lato funzionale.

**Comment by aleskandro** [comment]
@silviabooks

**Comment by silviabooks** [comment]
Vero, un minimo ci vuole.. però non vorrei il tutto diventi troppo complicato

**Comment by aleskandro** [comment]
https://blog.knoldus.com/2017/07/08/providing-security-using-akka-http/
https://doc.akka.io/docs/akka/1.2/scala/security.html
https://doc.akka.io/docs/akka/2.4.2-RC1/java/http/routing-dsl/request-vals/http-basic-authenticator.html

**Comment by aleskandro** [comment]
@silviabooks, da adesso, per accedere a tutte le api (come admin)

con curl:

```bash
 curl -XPOST -u 'silvia@scala:pass' -H "Content-Type: application/json" http://localhost:8080/events --data '{ "name": "sdfEventName2", "date": "2017-01-01T12:45:00.000Z", "category": "asd", "description": "saasas", "_id":"null", "quantity": 3, "price":12.2 }' -v
```

in js/Angular:

definiamo la variabile, da mantenere costante nello storageService.js per il momento

```js
var auth = $base64.encode("silvia@scala:pass"), 
```

in ogni request $http, aggiungiamo tra i field del primo argomento
```js
$http({method: 'GET', headers: {"Authorization": "Basic " + auth}....
```
appena e' completa la ui, sistemiamo l'assegnazione di quella variabile in qualche modo
