### ISSUE TITLE
Ridondanza nel codice delle routes

### ISSUE THREAD

**Issue by aleskandro** [silviabooks/scala-project#9]
Sistemando il controller per gli eventi in maniera omogenea rispetto alle risposte da fornire, viene fuori che la definizione delle route (vedi router.EventsRouter) continue MOLTO codice ridondante.

```scala
  } ~ path("categories") {
        get {
          onSuccess(eventHandler ? GetCategories) {
            case r: Array[String] =>
              complete(r)
            case r: StatusCode =>
              complete(r)
            case _ =>
              complete(StatusCodes.InternalServerError)
          }
        }
      } ~ path(Segment) { eventId =>
        get {
          onSuccess(eventHandler ? GetEvent(eventId)) {
            case r: Array[Event] =>
              complete(r)
            case r: StatusCode =>
              complete(r)
            case _ =>
              complete(StatusCodes.InternalServerError)
          }
        } ~ put {
          entity(as[Event]) { event =>
            onSuccess(eventHandler ? PutEvent(eventId, event)) {
              case r: StatusCode =>
                complete(r)
              case _ =>
                complete(StatusCodes.InternalServerError)
            }
          }
        } ~ delete {
          onSuccess(eventHandler ? DeleteEvent(eventId)) {
            case r: StatusCode =>
              complete(r)
            case _ =>
              complete(StatusCodes.InternalServerError)
          }
```

@silviabooks non sto riescendo per il momento a trovare un modo per rendere una 'variabile' il blocco { .*(case .*)* }

Provi anche tu a dare un'occhiata in giro?

**Comment by silviabooks** [comment]
Ok, ora vedo cosa trovo ✌

**Comment by silviabooks** [comment]
Neanche io ho trovato niente, la documentazione è poverella purtroppo :/
Secondo me dobbiamo assupparci la ridondanza perchè quel blocco è tipo il corpo della funzione onSuccess.. non so se prendere i vari case e metterli in una funzione a parte sia "legale", potrei provare ma sono pessimista

**Comment by aleskandro** [comment]
Alcune prove le ho fatte io senza successo ma un modo ci sara', in caso guardiamo di nuovo piu' in avanti al termine.

**Comment by silviabooks** [comment]
ok :+1:

**Comment by aleskandro** [comment]
chiudo, mi siddiai.

**Comment by silviabooks** [comment]
Perfetto, fold XD
